name: "Linter Evaluator"
description: "Evaluate linter for Tryber projects in android and ios"
inputs:
  linter-output:
    description: "Linter output"
    required: true
  pr-number:
    description: "Pull request number"
    required: true 
outputs:
  result:
    description: "Linter evaluation"
runs:
  using: "composite"
  steps:
    - name: Set up Nodejs 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Gradle cache
        uses: gradle/gradle-build-action@v2

      - name: Run detekt 
        run: ./gradlew detekt
        shell: bash

      - name: analyze results
        run: node $GITHUB_ACTION_PATH/dist/index.js
        shell: bash
        env:
          INPUT_PR_AUTHOR_USERNAME: ${{inputs.pr_author_username}}